backend:
  name: git-gateway
  repo: Hyperobjekt/untd-site
  branch: production # Optional, defaults to master. Update this to draw from the correct branch when working locally and when deployed.

local_backend: true # Switch off when deployed.
publish_mode: editorial_workflow
media_folder: /src/content/uploads
public_folder: /uploads

collections:
  - label: 'Language Pack'
    name: 'language'
    extension: json
    editor:
      preview: false
    files:
      - label: 'Site Language Pack'
        name: 'site'
        file: './src/content/lang/site.json'
        fields:
          - {
              label: 'English',
              name: 'en_US',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Site title',
                    name: 'SITE_TITLE',
                    widget: string,
                    hint: 'Site title in English, displayed in explorer',
                  },
                ],
            }
      - label: 'Explorer Language Pack'
        name: 'explorer'
        file: '/src/content/lang/explorer.json'
        fields:
          - {
              label: 'English',
              name: 'en_US',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Site title',
                    name: 'SITE_TITLE',
                    widget: string,
                    hint: 'Site title in English, displayed in explorer',
                  },
                  {
                    label: 'Map loading notification',
                    name: 'MAP_LOADING_DATA',
                    widget: string,
                    hint: 'Map loading notification string, displayed in explorer while map data is loading',
                  },
                  {
                    label: 'Custom attribution for map',
                    name: 'MAP_UI_POWERED_BY',
                    widget: string,
                    hint: 'Custom attribution displayed on margin of map',
                  },
                ],
            }
  - label: 'Content pages'
    name: 'pages'
    create: false
    format: frontmatter
    extensions: mdx
    media_folder: /src/content/uploads
    public_folder: /uploads
    editor:
      preview: true
    files:
      - label: '404'
        name: '404'
        file: '/src/content/pages/404.mdx'
        fields:
          - { name: title, label: 'Page title', widget: string }
          - { name: 'subtitle', label: 'Page subtitle', widget: 'string' }
          - { name: date, label: Date, widget: datetime }
          - { name: 'description', label: 'Page description', widget: 'string' }
          - {
              name: keywords,
              label: 'Page keywords',
              widget: list,
              default: ['page', 'keywords', 'listed', 'here'],
            }
          - {
              name: 'socialShareImage',
              label: 'Social share image for this page',
              widget: 'image',
            }
          - { name: body, label: Body, widget: markdown }
      - name: 'about'
        label: 'About'
        file: '/src/content/pages/about.mdx'
        fields:
          - { name: 'title', label: 'Page title', widget: 'string' }
          - { name: 'subtitle', label: 'Page subtitle', widget: 'string' }
          - { name: date, label: Date, widget: datetime }
          - { name: 'description', label: 'Page description', widget: 'string' }
          - {
              name: keywords,
              label: 'Page keywords',
              widget: list,
              default: ['page', 'keywords', 'listed', 'here'],
            }
          - {
              name: 'socialShareImage',
              label: 'Social share image for this page',
              widget: 'image',
            }
          - { name: body, label: Body, widget: markdown }
          - { name: 'heroText', label: 'Hero Text', widget: 'markdown' }
          - {
              name: 'contentRows',
              label: 'Content Rows',
              widget: 'list',
              fields:
                [
                  { name: 'rowText', label: 'Row Text', widget: 'markdown' },
                  { name: 'rowImage', label: 'Row Image', widget: 'image' },
                ],
            }
          - {
              name: 'fullWidthImage',
              label: 'Full Width Image',
              widget: 'image',
            }
          - {
              name: 'fullWidthText',
              label: 'Full Width Text',
              widget: 'markdown',
            }
          - {
              name: 'researchHeading',
              label: 'Research Heading',
              widget: 'markdown',
            }
          - {
              name: 'researchSubheading',
              label: 'Research Subheading',
              widget: 'markdown',
            }
          - {
              name: 'aboutTheCenterIntro',
              label: 'About The Center Intro',
              widget: 'markdown',
            }
          - {
              name: 'aboutTheCenterContent',
              label: 'About The Center Content',
              widget: 'markdown',
            }
      - name: 'contact'
        label: 'Contact'
        file: '/src/content/pages/contact.mdx'
        fields:
          - { name: 'title', label: 'Page title', widget: 'string' }
          - { name: 'subtitle', label: 'Page subtitle', widget: 'string' }
          - { name: date, label: Date, widget: datetime }
          - { name: 'description', label: 'Page description', widget: 'string' }
          - {
              name: keywords,
              label: 'Page keywords',
              widget: list,
              default: ['page', 'keywords', 'listed', 'here'],
            }
          - {
              name: 'socialShareImage',
              label: 'Social share image for this page',
              widget: 'image',
            }
          - { name: body, label: Body, widget: markdown }
      - name: 'explorer'
        label: 'Explorer'
        file: '/src/content/pages/explorer.mdx'
        fields:
          - { name: 'title', label: 'Page title', widget: 'string' }
          - { name: 'subtitle', label: 'Page subtitle', widget: 'string' }
          - { name: date, label: Date, widget: datetime }
          - { name: 'description', label: 'Page description', widget: 'string' }
          - {
              name: keywords,
              label: 'Page keywords',
              widget: list,
              default: ['page', 'keywords', 'listed', 'here'],
            }
          - {
              name: 'socialShareImage',
              label: 'Social share image for this page',
              widget: 'image',
            }
          - { name: body, label: Body, widget: markdown }
      - name: 'faq'
        label: 'FAQ'
        file: '/src/content/pages/faq.mdx'
        fields:
          - { name: 'title', label: 'Page title', widget: 'string' }
          - { name: 'subtitle', label: 'Page subtitle', widget: 'string' }
          - { name: date, label: Date, widget: datetime }
          - { name: 'description', label: 'Page description', widget: 'string' }
          - {
              name: keywords,
              label: 'Page keywords',
              widget: list,
              default: ['page', 'keywords', 'listed', 'here'],
            }
          - {
              name: 'socialShareImage',
              label: 'Social share image for this page',
              widget: 'image',
            }
          - {
              name: 'questions',
              label: 'Questions',
              widget: 'list',
              summary: '{{fields.question}}',
              fields:
                [
                  { name: 'question', label: 'Question', widget: 'string' },
                  { name: 'answer', label: 'Answer', widget: 'markdown' },
                ],
            }
          - { name: body, label: Body, widget: markdown }
      - name: 'home'
        label: 'Home'
        file: '/src/content/pages/home.mdx'
        fields:
          - { name: 'title', label: 'Page title', widget: 'string' }
          - { name: 'subtitle', label: 'Page subtitle', widget: 'string' }
          - { name: date, label: Date, widget: datetime }
          - { name: 'description', label: 'Page description', widget: 'string' }
          - {
              name: keywords,
              label: 'Page keywords',
              widget: list,
              default: ['page', 'keywords', 'listed', 'here'],
            }
          - {
              name: 'socialShareImage',
              label: 'Social share image for this page',
              widget: 'image',
            }
          - { name: 'heroImage', label: 'Hero Module Image', widget: 'image' }
          - {
              name: 'heroSubheading',
              label: 'Hero Subheading',
              widget: 'string',
            }
          - { name: 'graphImage', label: 'Graph Module Image', widget: 'image' }
          - {
              name: 'graphCitation',
              label: 'Graph Module Citation',
              widget: 'string',
            }
          - {
              name: 'graphHeading',
              label: 'Graph Module Heading',
              widget: 'string',
            }
          - {
              name: 'graphSubheading',
              label: 'Graph Module Subheading',
              widget: 'markdown',
            }
          - { name: 'engageIntro', label: 'Engage Intro', widget: 'string' }
          - {
              name: 'engageCards',
              label: 'Engage Cards',
              widget: 'list',
              summary: '{{fields.cardTitle}}',
              fields:
                [
                  { name: 'cardTitle', label: 'Card Title', widget: 'string' },
                  {
                    name: 'cardHeading',
                    label: 'Card Heading',
                    widget: 'markdown',
                  },
                  {
                    name: 'cardSubheading',
                    label: 'Card Subheading',
                    widget: 'string',
                  },
                  {
                    name: 'cardImage',
                    label: 'Card Image',
                    widget: 'image',
                    required: false,
                  },
                  {
                    name: 'isLibraryCallout',
                    label: 'Is Library Callout',
                    widget: 'boolean',
                    required: false,
                  },
                  {
                    name: 'cardLinks',
                    label: 'Card Links',
                    widget: 'list',
                    fields:
                      [
                        {
                          name: 'linkText',
                          label: 'Link Text',
                          widget: 'string',
                        },
                        {
                          name: 'linkUrl',
                          label: 'Link Url',
                          widget: 'string',
                        },
                      ],
                  },
                ],
            }
          - { name: body, label: Body, widget: markdown }
      - name: 'research-library'
        label: 'Research Library'
        file: '/src/content/pages/research-library.mdx'
        fields:
          - { name: 'title', label: 'Page title', widget: 'string' }
          - { name: 'subtitle', label: 'Page subtitle', widget: 'string' }
          - { name: date, label: Date, widget: datetime }
          - { name: 'description', label: 'Page description', widget: 'string' }
          - {
              name: keywords,
              label: 'Page keywords',
              widget: list,
              default: ['page', 'keywords', 'listed', 'here'],
            }
          - {
              name: 'socialShareImage',
              label: 'Social share image for this page',
              widget: 'image',
            }
          - {
              name: 'libraryHeroText',
              label: 'Library Hero Text',
              widget: 'markdown',
            }
          - {
              name: 'libraryDescription',
              label: 'Library Description',
              widget: 'markdown',
            }
          - {
              name: 'libraryDescriptionImage',
              label: 'Library Description Image',
              widget: 'image',
            }
          - {
              name: 'libraryTopicsHeading',
              label: 'Library Topics Heading',
              widget: 'markdown',
            }
          - {
              name: 'libraryTopicsHeadingImage',
              label: 'Library Topics Heading Image',
              widget: 'image',
            }
          - name: 'body'
            label: 'Body'
            widget: 'markdown'
          - name: 'researchItems'
            label: 'Research Items'
            widget: 'list'
            fields:
              - { name: 'label', label: 'Label for ', widget: 'string' }
              - {
                  name: 'displayOnHomePage',
                  label: 'Display on Home Page',
                  widget: 'boolean',
                  required: false,
                }
              - { name: 'topic_area', label: 'Topic area', widget: 'string' }
              - { name: 'type', label: 'Type', widget: 'string' }
              - { name: 'link', label: 'Link', widget: 'string' }
              - {
                  name: 'quick_citation',
                  label: 'Quick citation',
                  widget: 'string',
                }
              - { name: 'authors', label: 'Authors', widget: 'string' }
              - { name: 'year', label: 'Year', widget: 'string' }
              - {
                  name: 'full_citation',
                  label: 'Full citation',
                  widget: 'string',
                }
              - {
                  name: 'item_color',
                  label: 'Item Color',
                  widget: 'color',
                  allowInput: true,
                  default: '#000000',
                }
              - {
                  name: 'item_content',
                  label: 'Item Content',
                  widget: 'markdown',
                  required: false,
                }
              - {
                  name: 'item_references',
                  label: 'Item References',
                  widget: 'markdown',
                  required: true,
                  default: '\n',
                }
      - name: 'use-cases'
        label: 'Use Cases'
        file: '/src/content/pages/use-cases.mdx'
        fields:
          - { name: 'title', label: 'Page title', widget: 'string' }
          - { name: 'subtitle', label: 'Page subtitle', widget: 'string' }
          - { name: date, label: Date, widget: datetime }
          - { name: 'description', label: 'Page description', widget: 'string' }
          - {
              name: keywords,
              label: 'Page keywords',
              widget: list,
              default: ['page', 'keywords', 'listed', 'here'],
            }
          - {
              name: 'socialShareImage',
              label: 'Social share image for this page',
              widget: 'image',
            }
          - { name: 'heroText', label: 'Hero Text', widget: 'markdown' }
          - {
              name: 'useCasesRows',
              label: 'Use Cases Rows',
              widget: 'list',
              fields:
                [
                  { name: 'rowText', label: 'Row Text', widget: 'markdown' },
                  { name: 'rowImage', label: 'Row Image', widget: 'image' },
                ],
            }
          - {
              name: 'worksheetsHeading',
              label: 'Worksheets Heading',
              widget: 'string',
            }
          - {
              name: 'worksheets',
              label: 'Worksheets',
              widget: 'list',
              fields:
                [
                  {
                    name: 'sheetEyebrow',
                    label: 'Sheet Eyebrow',
                    widget: 'string',
                  },
                  {
                    name: 'sheetText',
                    label: 'Sheet Text',
                    widget: 'markdown',
                  },
                  { name: 'sheetImage', label: 'Sheet Image', widget: 'image' },
                  {
                    name: 'sheetFile',
                    label: 'Sheet File',
                    widget: 'file',
                    media_folder: '/static/uploads',
                    public_folder: '/uploads',
                  },
                ],
            }
          - { name: body, label: Body, widget: markdown }
